### ISSUE TITLE
Dynamic Inventory - unrecognized arguments

### ISSUE THREAD

**Issue by m-j-ray** [device42/ansible_device42#13]
I receive the following error when using the dynamic inventory script:

```
[WARNING]:  * Failed to parse /Users/my-user/git/ansible-home/inventory/ansible_device42/d42_ansible_dynamic_inventory.py with script plugin:
Inventory script (/Users/my-user/git/ansible-home/inventory/ansible_device42/d42_ansible_dynamic_inventory.py) had an execution error: usage:
d42_ansible_dynamic_inventory.py [-h] d42_ansible_dynamic_inventory.py: error: unrecognized arguments: --list
```

According the [Ansible Script Inventory Plugin](https://docs.ansible.com/ansible/latest/plugins/inventory/script.html#synopsis), the source must accept `--list` as an argument. 

Looks like this was working and broken by [commit 156c48f](https://github.com/device42/ansible_device42/commit/156c48f45ba8ab205429110adf02bf457a3dd0d4?diff=unified). Reverting this change solves the problem.

**Comment by ghost** [comment]
thanks for the report @m-j-ray , fixed
