### ISSUE TITLE
Getting custom fields: Response Status Code 500

### ISSUE THREAD

**Issue by Marschelloss** [device42/ansible_device42#18]
D42 version: 16.12.00.1590694668 

Command used: `ansible-inventory -i vnp.d42.yml --graph`

Results in empty inventory. Seems like the action `Getting custom fields` fails:

```
Response Status: 200
Getting MAC Addresses
Response Status: 200
Getting HDD Details
Response Status: 200
Getting Device External Links
Response Status: 200
Getting Device Entitlements
Response Status: 200
Getting Custom Fields
Response Status: 500
'str' object has no attribute 'get'
@all:
  |--@ungrouped:
```

After some digging, the used API Request doensn't work:

![image](https://user-images.githubusercontent.com/10983729/89030420-b95d1e80-d330-11ea-8631-f238299bfba2.png)

Is there a way to fix this?

Thanks!

**Comment by osanchez42** [comment]
Hey @DonHansDampf, I believe this may be a compatibility issue with this custom fields query. I don't believe version 16.12.00 of D42 has a notes field on the custom fields. Try this new query and let me know what you get back. I will most likely remove this field from the query in order to continue support for 161200. 


```
select
                view_device_v1.device_pk,
                view_device_v1.name,
                custom_field.key as custom_field_key,
                custom_field.value as custom_field_value
                from view_device_v1
                inner join (select device_fk, type, key,
                                  (CASE
                                    WHEN view_device_custom_fields_v1.type = 'Related Field'
                                        THEN (CASE
                                                WHEN view_device_custom_fields_v1.related_model_name = 'endusers'
                                                THEN (SELECT name FROM view_enduser_v1 WHERE view_enduser_v1.enduser_pk = view_device_custom_fields_v1.value :: int)
                                                ELSE 'not available'
                                                END)
                                    ELSE view_device_custom_fields_v1.value
                                    END) as value
                from view_device_custom_fields_v1) custom_field
                on view_device_v1.device_pk = custom_field.device_fk
```

**Comment by Marschelloss** [comment]
Hi @osanchez42 ,

sadly I get the same result:

![image](https://user-images.githubusercontent.com/10983729/89202930-0270d500-d5b4-11ea-9ed8-f72907fda8ff.png)

**Comment by osanchez42** [comment]
Hey @DonHansDampf, I recommend testing doqls by saving them within Tools > Integrations > Saved Doql Queries tab. Create a new entry and paste in the doql. This will create a link that should run the doqls in the correct format and hopefully help see if there are any syntax issues

**Alternatively, using the following curl request with your device42 url and username and pass will work.** 

curl --location --request GET 'http://username:password@192.168.92.130/services/data/v1.0/query/?query=select%0Aview_device_v1.device_pk,%0Aview_device_v1.name,%0Acustom_field.key%20as%20custom_field_key,%0Acustom_field.value%20as%20custom_field_value%0Afrom%20view_device_v1%0Ainner%20join%20(select%20device_fk,%20type,%20key,%0A%09%09%09%09%20%20(CASE%0A%09%09%09%09%09WHEN%20view_device_custom_fields_v1.type%20=%20%27Related%20Field%27%0A%09%09%09%09%09%09THEN%20(CASE%0A%09%09%09%09%09%09%09%09WHEN%20view_device_custom_fields_v1.related_model_name%20=%20%27endusers%27%0A%09%09%09%09%09%09%09%09THEN%20(SELECT%20name%20FROM%20view_enduser_v1%20WHERE%20view_enduser_v1.enduser_pk%20=%20view_device_custom_fields_v1.value%20::%20int)%0A%09%09%09%09%09%09%09%09ELSE%20%27not%20available%27%0A%09%09%09%09%09%09%09%09END)%0A%09%09%09%09%09ELSE%20view_device_custom_fields_v1.value%0A%09%09%09%09%09END)%20as%20value%0Afrom%20view_device_custom_fields_v1)%20custom_field%0Aon%20view_device_v1.device_pk%20=%20custom_field.device_fk&header=yes&output_type=csv'

**A bit simpler to see what is being passed in params**

curl --location --request GET 'http://username:password@192.168.92.130/services/data/v1.0/query/?query=select%20*%20from%20view_device_v1&header=yes&output_type=csv'

**Comment by Marschelloss** [comment]
Hi @osanchez42 ,

already tried that and got an empty csv. Though that the query view would be better. Sadly the same result if I pass the DOQL directly:

```
❯ curl --location --request GET 'https://user:pass@device42/services/data/v1.0/query/?query=select%0Aview_device_v1.device_pk,%0Aview_device_v1.name,%0Acustom_field.key%20as%20custom_field_key,%0Acustom_field.value%20as%20custom_field_value%0Afrom%20view_device_v1%0Ainner%20join%20(select%20device_fk,%20type,%20key,%0A%09%09%09%09%20%20(CASE%0A%09%09%09%09%09WHEN%20view_device_custom_fields_v1.type%20=%20%27Related%20Field%27%0A%09%09%09%09%09%09THEN%20(CASE%0A%09%09%09%09%09%09%09%09WHEN%20view_device_custom_fields_v1.related_model_name%20=%20%27endusers%27%0A%09%09%09%09%09%09%09%09THEN%20(SELECT%20name%20FROM%20view_enduser_v1%20WHERE%20view_enduser_v1.enduser_pk%20=%20view_device_custom_fields_v1.value%20::%20int)%0A%09%09%09%09%09%09%09%09ELSE%20%27not%20available%27%0A%09%09%09%09%09%09%09%09END)%0A%09%09%09%09%09ELSE%20view_device_custom_fields_v1.value%0A%09%09%09%09%09END)%20as%20value%0Afrom%20view_device_custom_fields_v1)%20custom_field%0Aon%20view_device_v1.device_pk%20=%20custom_field.device_fk&header=yes&output_type=csv'
device_pk,name,custom_field_key,custom_field_value

```

**Comment by osanchez42** [comment]
@DonHansDampf 
The results you see appear to be accurate. These are the headers for the fields retrieved by doql, if there are no records it will be empty. The only custom fields retrieved at the moment are device custom fields, all data types are supported with the exception of related fields. The only related field that works is the end-user related field. This requires configuration by device42 admin. By default device42 does not include custom fields. If there is a custom field that you configured for devices that is not being retrieved please let me know

**Comment by Marschelloss** [comment]
Hi @osanchez42 ,
my bad. While using the Query at different locations I forgot that I **don't** expect any output ;) Sorry!

Just to be sure, I updated the the query in the d42.py file and it also works!

**Comment by osanchez42** [comment]
Thats great news @DonHansDampf. I have a PR that will resolve this issue and will be updating the ansible galaxy listing with this version 1.1.1 which includes this fix once merged. I am marking this ticket as resolved. If you encounter any issues please feel free to open an issue here or contact us through our support methods listed on our site. Have a great day
