### ISSUE TITLE
static inventory doesn't work with GROUP_BY = 'tag'

### ISSUE THREAD

**Issue by keepwatch** [device42/ansible_device42#2]
I followed the instructions to run the script and got an inventory file that looked like:
```
[group1]
hosts

[group2]
hosts

[None]
host1
host2
host3
...
```

The code is just printing the name of the nested dict 'hosts' instead of the values. I fixed that problem, and then fixed the next problem (hosts in the 'None' group don't have the nested dict), so this script now works as designed.

**Comment by keepwatch** [comment]
I just opened #3 to fix this.

**Comment by ghost** [comment]
hi @keepwatch, thank you for feedback, I be able to reproduce this bug. Unfortunately I can't accept your pull request because while it fix current issue correct it also breaks another parts of the program when we use in different mode. 

Fix for the issue above I will prepare soon. Thanks.

**Comment by ghost** [comment]
@keepwatch please check how it working for you now, I've pushed fix. Thanks.

**Comment by keepwatch** [comment]
@tolyadouble that works! Thanks for the prompt response.
