### ISSUE TITLE
exception imp.load_source('conf', 'conf')

### ISSUE THREAD

**Issue by c-linse** [device42/ansible_device42#5]
i tryed to start the script with my credentials in conf file, but i run directly in the exception in the lib.py after loading the conf file. Permissions are set

**Comment by ghost** [comment]
hello @D4ywa1k3r, can you post trace stack here? Thanks.

**Comment by c-linse** [comment]
Hello @tolyadouble, sure. Here my Stacktrace. I dont know why, but the conf-file can now be load. The exception is still there. 
Here ist my stacktrace:
`/usr/bin/python2.7 /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 52068 --file /Users/user/Downloads/ansible_device42/d42_ansible_inventory_hostfile.py
pydev debugger: process 2493 is connecting

Connected to pydev debugger (build 182.3911.33)
<traceback object at 0x1040b72d8>
(<type 'exceptions.TypeError'>, TypeError("'module' object has no attribute '__getitem__'",), <traceback object at 0x1040b72d8>)
None
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/user/Downloads/ansible_device42/d42_ansible_inventory_hostfile.py", line 7, in <module>
    conf = get_conf()
  File "/Users/user/Downloads/ansible_device42/lib.py", line 29, in get_conf
    print traceback.print_stack()
Please set D42_URL environ.
`

**Comment by ghost** [comment]
@D4ywa1k3r possible issue with pycharm, another way to set all settings as system env.

**Comment by ghost** [comment]
@D4ywa1k3r does it work for you?

**Comment by c-linse** [comment]
That was an issue with pycharm. everything is working now. reason was a restart...

**Comment by ghost** [comment]
Thanks for information @D4ywa1k3r , then I close the issue.
