### ISSUE TITLE
multiple tags, but one group

### ISSUE THREAD

**Issue by c-linse** [device42/ansible_device42#6]
Hi all,
`
GROUP_BY_QUERY = 'SELECT vd.name, vd.tags, vi.ip_address FROM view_device_v1 vd join view_ipaddress_v1 vi on vd.device_pk = vi.device_fk WHERE vd.tags=\'all,role_percona_xtradb,dc_de_fra_bcknd_pdymisc,role_apache\''`
`GROUP_BY_FIELD = 'tags'`
`GROUP_BY_REFERENCE_FIELD = 'ip_address'`

That is my content of the conf file.
Expected output:
```
[all]
Specific_instance1
 
[role_percona_xtradb]
Specific_instance1
 
[dc_de_fra_bcknd_pdymisc]
Specific_instance1
 
[role_apache]
Specific_instance1
```
But i got this output
```
[all,role_percona_xtradb,dc_de_fra_bcknd_pdymisc,role_apache]
Specific_instance1
```
As far as i know can't ansible work with that format.
Is there a workaround around this issue?

**Comment by c-linse** [comment]
i modified for myself the lib.py in the Ansible class in function "get_grouping"
as follow you can see my code and this will be sufficient for me..
 ```
groups = {}
        for object_ in objects:
            try:
                fqdn = object_[self.conf['GROUP_BY_FQDN']]
                ip = object_[self.conf['GROUP_BY_REFERENCE_FIELD']]
                both = fqdn + ' ansible_host=' + ip
                if object_[self.conf['GROUP_BY_FIELD']] not in groups:
                    __ = object_[self.conf['GROUP_BY_FIELD']].split(',')
                    for tag in __:
                        groups[tag] = []
                        groups[tag].append(both)
            except Exception as e:
                print object_
                sys.exit()
        return groups
```

**Comment by ghost** [comment]
hello @D4ywa1k3r, we did a new feature and applied it as the last commit, so now you can split result values by comma.
I close this issue, thanks.
