### ISSUE TITLE
UnicodeEncodeError in get_list_from_csv 

### ISSUE THREAD

**Issue by TLMcNulty** [device42/ansible_device42#9]
Thought this was due to not running python 2.7 as I was in 2.6 by default. 
Installed 2.7 and running it gets the same Unicode error due to this decode call

```
#/opt/python-2.7.7/bin/python d42_ansible_inventory_hostfile.py
Traceback (most recent call last):
  File "d42_ansible_inventory_hostfile.py", line 9, in <module>
    groups = ansible.get_grouping(Device42(conf).doql())
  File "/home/tmcnulty/git/ansible_device42/lib.py", line 80, in doql
    return self.get_list_from_csv(self.fetcher(url, self.query))
  File "/home/tmcnulty/git/ansible_device42/lib.py", line 84, in get_list_from_csv
    f = StringIO(text.decode("utf-8"))
  File "/opt/python-2.7.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 234153-234154: ordinal not in range(128)
```

**Comment by TLMcNulty** [comment]
Update:
I started indexing the str to figure out what was causing this, it's caused by characters that are well outside the range allowed, I didn't want to mess with encoding/decoding

`SITE-999Ã¢E-3-PDU-B,Unspecified`

Dirty data is obviously the cause, I found it simplest to fix the device causing this.

**Comment by TLMcNulty** [comment]
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 234153-234154: ordinal not in range(128)`

`        print r.text[234125:234153]
        print r.text[234153]
        print r.text[234154]`

`olbox100,Unspecified
SITE-999
Ã
¢`

**Comment by ghost** [comment]
Hello @TLMcNulty, thank you for the report. I've sent a commit where we encode text into "utf-8" and fix the issue.
